import type { Lesson } from "../schema.js";

const START = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
const EMPTY = "8/8/8/8/8/8/8/8 w - - 0 1";

export const stage0: Lesson[] = [
  {
    slug: "taxta",
    stage: 0,
    title: "Shaxmat taxtasi",
    summary: "Kataklar, vertikallar, gorizontallar va koordinatalar.",
    steps: [
      {
        type: "text",
        text: "Shaxmat 64 katakli taxtada o'ynaladi: 8 qator va 8 ustun. Oq va qora kataklar navbatma-navbat keladi. O'yinchidan qaraganda o'ng pastki burchakdagi katak doim oq bo'ladi.",
        fen: EMPTY,
        highlights: ["h1"],
      },
      {
        type: "text",
        text: "Ustunlar — vertikallar — a dan h gacha harflar bilan belgilanadi. Qatorlar — gorizontallar — 1 dan 8 gacha raqamlar bilan belgilanadi.",
        fen: EMPTY,
        highlights: ["e1", "e2", "e3", "e4", "e5", "e6", "e7", "e8"],
      },
      {
        type: "text",
        text: "Har bir katakning nomi vertikal harfi va gorizontal raqamidan tuziladi. Belgilangan katak — e4.",
        speech: "Har bir katakning nomi vertikal harfi va gorizontal raqamidan tuziladi. Belgilangan katak — e to'rt.",
        fen: EMPTY,
        highlights: ["e4"],
      },
      {
        type: "quiz",
        text: "Belgilangan katak qanday nomlanadi?",
        fen: EMPTY,
        highlights: ["c6"],
        options: ["c6", "f3", "c3"],
        answer: 0,
        explanation: "Vertikal — c, gorizontal — 6. Demak, katak c6.",
      },
      {
        type: "text",
        text: "O'yin boshida donalar shunday turadi. Oqlar 1- va 2-gorizontalda, qoralar 7- va 8-gorizontalda. Birinchi bo'lib oqlar yuradi.",
        fen: START,
      },
      {
        type: "quiz",
        text: "Oq farzin o'yin boshida qaysi katakda turadi?",
        fen: START,
        options: ["e1", "d1", "d8"],
        answer: 1,
        explanation: "Farzin o'z rangidagi katakda turadi: oq farzin oq d1 katakda, shoh esa uning yonida, e1 da.",
      },
    ],
  },
  {
    slug: "ruh",
    stage: 0,
    title: "Ruh",
    summary: "To'g'ri chiziq bo'ylab yuradigan dona.",
    steps: [
      {
        type: "text",
        text: "Ruh to'g'ri chiziq bo'ylab — vertikal yoki gorizontal yo'nalishda — istalgan masofaga yuradi. Yo'lida boshqa dona bo'lsa, undan o'tib keta olmaydi.",
        fen: "8/8/8/8/3R4/8/8/8 w - - 0 1",
        arrows: [
          ["d4", "d8"],
          ["d4", "h4"],
          ["d4", "d1"],
          ["d4", "a4"],
        ],
      },
      {
        type: "stars",
        text: "Ruhni yurib, barcha yulduzlarni yig'ing.",
        fen: "8/8/8/8/8/8/8/R7 w - - 0 1",
        stars: ["a6", "f6", "f2"],
      },
      {
        type: "stars",
        text: "Yana bir mashq: yulduzlarni iloji boricha kam yurish bilan yig'ing.",
        fen: "8/8/8/8/8/8/8/7R w - - 0 1",
        stars: ["c1", "c8", "h8"],
      },
      {
        type: "move",
        text: "Ruh raqib donasi turgan katakka yurib, uni urib olishi mumkin. Ruh bilan qora otni urib oling.",
        fen: "8/8/8/3n4/8/8/8/3R4 w - - 0 1",
        solutions: ["d1d5"],
        hint: "Ot ruh bilan bir vertikalda turibdi.",
        success: "Barakalla! Ot taxtadan olib tashlandi.",
      },
    ],
  },
  {
    slug: "fil",
    stage: 0,
    title: "Fil",
    summary: "Diagonal bo'ylab yuradigan dona.",
    steps: [
      {
        type: "text",
        text: "Fil faqat diagonal bo'ylab istalgan masofaga yuradi. Shuning uchun u o'yin oxirigacha bir xil rangdagi kataklarda qoladi.",
        fen: "8/8/8/8/3B4/8/8/8 w - - 0 1",
        arrows: [
          ["d4", "h8"],
          ["d4", "a7"],
          ["d4", "g1"],
          ["d4", "a1"],
        ],
      },
      {
        type: "stars",
        text: "Fil bilan barcha yulduzlarni yig'ing.",
        fen: "8/8/8/8/8/8/8/2B5 w - - 0 1",
        stars: ["e3", "g5", "d8"],
      },
      {
        type: "quiz",
        text: "Qora katakda turgan fil oq katakka o'ta oladimi?",
        options: ["Ha", "Yo'q"],
        answer: 1,
        explanation: "Diagonal bo'ylab yurganda katak rangi o'zgarmaydi, shuning uchun fil doim bir rangdagi kataklarda qoladi.",
      },
      {
        type: "move",
        text: "Fil bilan qora ruhni urib oling.",
        fen: "8/8/6r1/8/8/8/2B5/8 w - - 0 1",
        solutions: ["c2g6"],
        hint: "Ruh fil bilan bir diagonalda turibdi.",
        success: "To'g'ri! Fil ruhni oldi — bu katta yutuq.",
      },
    ],
  },
  {
    slug: "farzin",
    stage: 0,
    title: "Farzin",
    summary: "Eng kuchli dona: ruh va filning kuchi birga.",
    steps: [
      {
        type: "text",
        text: "Farzin — eng kuchli dona. U ruh va filning yurishlarini birlashtiradi: to'g'ri chiziq va diagonal bo'ylab istalgan masofaga yuradi.",
        fen: "8/8/8/8/3Q4/8/8/8 w - - 0 1",
        arrows: [
          ["d4", "d8"],
          ["d4", "h8"],
          ["d4", "h4"],
          ["d4", "g1"],
          ["d4", "d1"],
          ["d4", "a1"],
          ["d4", "a4"],
          ["d4", "a7"],
        ],
      },
      {
        type: "stars",
        text: "Farzin bilan barcha yulduzlarni yig'ing.",
        fen: "8/8/8/8/8/8/8/3Q4 w - - 0 1",
        stars: ["h5", "e8", "a4"],
      },
      {
        type: "move",
        text: "Farzin bilan qora filni urib oling.",
        fen: "8/8/8/1b6/8/8/8/5Q2 w - - 0 1",
        solutions: ["f1b5"],
        hint: "Fil farzin bilan bir diagonalda turibdi.",
        success: "Ajoyib! Farzin istalgan yo'nalishda uzoqqa ura oladi.",
      },
    ],
  },
  {
    slug: "shoh",
    stage: 0,
    title: "Shoh",
    summary: "Eng muhim dona va uning yurishi.",
    steps: [
      {
        type: "text",
        text: "Shoh — eng muhim dona. U istalgan yo'nalishda faqat bir katakka yuradi.",
        fen: "8/8/8/8/3K4/8/8/8 w - - 0 1",
        highlights: ["c5", "d5", "e5", "c4", "e4", "c3", "d3", "e3"],
      },
      {
        type: "stars",
        text: "Shoh bilan barcha yulduzlarni yig'ing.",
        fen: "8/8/8/8/8/8/8/4K3 w - - 0 1",
        stars: ["e3", "g4", "f6"],
      },
      {
        type: "text",
        text: "Shohni urib bo'lmaydi va uni hujum ostidagi katakka qo'yish mumkin emas. Shuning uchun ikki shoh hech qachon yonma-yon turmaydi.",
        fen: "8/8/8/3k4/8/3K4/8/8 w - - 0 1",
        highlights: ["c4", "d4", "e4"],
      },
    ],
  },
  {
    slug: "ot",
    stage: 0,
    title: "Ot",
    summary: "«G» harfi shaklida yuradigan va sakraydigan dona.",
    steps: [
      {
        type: "text",
        text: "Ot «G» harfi shaklida yuradi: bir tomonga ikki katak, keyin yon tomonga bir katak. Ot boshqa donalar ustidan sakrab o'ta oladigan yagona dona.",
        fen: "8/8/8/8/3N4/8/8/8 w - - 0 1",
        highlights: ["b5", "c6", "e6", "f5", "f3", "e2", "c2", "b3"],
      },
      {
        type: "stars",
        text: "Ot bilan barcha yulduzlarni yig'ing.",
        fen: "8/8/8/8/8/8/8/1N6 w - - 0 1",
        stars: ["c3", "d5", "f6"],
      },
      {
        type: "stars",
        text: "Yana bir mashq. Ot har yurishda katak rangini almashtiradi — shuni hisobga oling.",
        fen: "8/8/8/8/8/8/8/6N1 w - - 0 1",
        stars: ["f3", "e5", "g6"],
      },
      {
        type: "move",
        text: "Ot bilan qora farzinni urib oling.",
        fen: "8/8/8/4q3/8/3N4/8/8 w - - 0 1",
        solutions: ["d3e5"],
        hint: "Ikki katak yuqoriga, bir katak o'ngga.",
        success: "Zo'r! Ot farzinni oldi.",
      },
    ],
  },
  {
    slug: "piyoda",
    stage: 0,
    title: "Piyoda",
    summary: "Oldinga yuradi, qiyshiq uradi.",
    steps: [
      {
        type: "text",
        text: "Piyoda faqat oldinga, bir katak yuradi. O'zining birinchi yurishida esa bir yoki ikki katak yura oladi.",
        fen: "8/8/8/8/8/8/4P3/8 w - - 0 1",
        arrows: [["e2", "e4"]],
      },
      {
        type: "move",
        text: "Piyodani ikki katak oldinga suring.",
        fen: "8/8/8/8/8/8/4P3/8 w - - 0 1",
        solutions: ["e2e4"],
        success: "To'g'ri! Birinchi yurishda piyoda ikki katak yura oladi.",
      },
      {
        type: "text",
        text: "Piyoda to'g'riga yuradi, lekin qiyshiq uradi: oldidagi diagonal katakda turgan raqib donasini oladi.",
        fen: "8/8/8/3p1n2/4P3/8/8/8 w - - 0 1",
        arrows: [
          ["e4", "d5"],
          ["e4", "f5"],
        ],
      },
      {
        type: "move",
        text: "Piyoda bilan qimmatroq donani — otni — urib oling.",
        fen: "8/8/8/3p1n2/4P3/8/8/8 w - - 0 1",
        solutions: ["e4f5"],
        hint: "Ot piyodadan qimmatroq.",
        success: "Barakalla! Piyoda otni oldi.",
      },
      {
        type: "quiz",
        text: "Piyoda orqaga yura oladimi?",
        options: ["Ha", "Yo'q"],
        answer: 1,
        explanation: "Piyoda hech qachon orqaga yurmaydi. Shuning uchun har bir piyoda yurishini o'ylab qiling.",
      },
    ],
  },
  {
    slug: "urish",
    stage: 0,
    title: "Donalarni urish",
    summary: "Raqib donasini qanday olish va qaysi birini olish kerak.",
    steps: [
      {
        type: "text",
        text: "Raqib donasi turgan katakka yurgan dona uni urib oladi. Urilgan dona taxtadan olib tashlanadi. O'z donangizni urib bo'lmaydi.",
      },
      {
        type: "move",
        text: "Himoyasiz qora otni urib oling.",
        fen: "k7/8/n7/8/8/8/8/R6K w - - 0 1",
        solutions: ["a1a6"],
        success: "To'g'ri!",
      },
      {
        type: "move",
        text: "Farzin ikki donani ura oladi. Qaysi birini olish xavfsiz? Himoyalanmagan donani oling.",
        fen: "4k3/3r4/8/7n/8/8/8/3Q2K1 w - - 0 1",
        solutions: ["d1h5"],
        hint: "Ruhni qora shoh himoya qilyapti: farzin uni olsa, shoh farzinni oladi.",
        success: "Ajoyib! Ruhni olsangiz, shoh farzinni urib olardi. Ot esa himoyasiz edi.",
      },
    ],
  },
  {
    slug: "shoh-berish",
    stage: 0,
    title: "Shoh berish",
    summary: "Shohga hujum va undan qutulishning uch yo'li.",
    steps: [
      {
        type: "text",
        text: "Shohga hujum qilish «shoh berish» deyiladi. Shoh berilgan tomon darhol shohni xavfdan qutqarishi shart — boshqa yurish qilib bo'lmaydi.",
        fen: "4k3/8/8/8/8/8/8/R3K3 w - - 0 1",
        arrows: [["a1", "a8"]],
      },
      {
        type: "move",
        text: "Ruh bilan qora shohga shoh bering.",
        fen: "4k3/8/8/8/8/8/8/R3K3 w - - 0 1",
        goal: "check",
        hint: "Ruhni qora shoh turgan gorizontalga olib boring.",
        success: "To'g'ri! Qora shoh hujum ostida.",
      },
      {
        type: "text",
        text: "Shohni qutqarishning uchta yo'li bor: shohni xavfsiz katakka olib qochish, hujum qilayotgan donani urib olish, yoki o'rtaga boshqa donani qo'yib to'sish.",
      },
      {
        type: "move",
        text: "Oq shohga shoh berildi! Hujum qilayotgan ruhni urib oling.",
        fen: "4k3/8/8/8/8/2N5/4r3/4K3 w - - 0 1",
        solutions: ["c3e2", "e1e2"],
        hint: "Ruhni ot ham, shoh ham ura oladi.",
        success: "Barakalla! Hujum qilgan dona yo'q qilindi.",
      },
      {
        type: "move",
        text: "Yana shoh berildi. Bu safar ot bilan o'rtani to'sing.",
        fen: "k7/8/8/8/8/4N3/8/r6K w - - 0 1",
        solutions: ["e3d1", "e3f1"],
        hint: "Otni birinchi gorizontalga, ruh va shoh orasiga qo'ying.",
        success: "To'g'ri! Ot hujum yo'lini to'sdi.",
      },
    ],
  },
  {
    slug: "mat",
    stage: 0,
    title: "Mat",
    summary: "O'yinning maqsadi: raqib shohini mat qilish.",
    steps: [
      {
        type: "text",
        text: "Agar shohga shoh berilgan bo'lsa va uni qutqarishning hech bir yo'li bo'lmasa — bu mat. Mat qilgan tomon g'alaba qiladi.",
      },
      {
        type: "text",
        text: "Bu pozitsiyada qora shoh mat: ruh unga shoh beryapti, qochishga esa o'z piyodalari to'sqinlik qiladi.",
        fen: "3R2k1/5ppp/8/8/8/8/8/6K1 b - - 1 1",
        arrows: [["d8", "g8"]],
      },
      {
        type: "move",
        text: "Bir yurishda mat qiling.",
        fen: "6k1/5ppp/8/8/8/8/8/3R2K1 w - - 0 1",
        goal: "mate",
        hint: "Qora shoh oxirgi gorizontda qamalib qolgan.",
        success: "Mat! Siz g'alaba qildingiz.",
      },
      {
        type: "move",
        text: "Farzin bilan bir yurishda mat qiling.",
        fen: "7k/8/6K1/8/8/8/8/1Q6 w - - 0 1",
        goal: "mate",
        hint: "Oq shoh g7 va h7 kataklarini nazorat qilyapti.",
        success: "Mat! Farzin va shoh birga ishladi.",
      },
      {
        type: "move",
        text: "Ruh bilan bir yurishda mat qiling.",
        fen: "k7/8/1K6/8/8/8/8/7R w - - 0 1",
        goal: "mate",
        hint: "Ruhni sakkizinchi gorizontga olib boring.",
        success: "Mat!",
      },
    ],
  },
  {
    slug: "pat",
    stage: 0,
    title: "Pat",
    summary: "Yurish yo'q, lekin shoh berilmagan — durang.",
    steps: [
      {
        type: "text",
        text: "Agar navbat kelgan tomonning shohiga shoh berilmagan bo'lsa-yu, lekin uning birorta ham qonuniy yurishi bo'lmasa — bu pat. Pat durang hisoblanadi.",
        fen: "7k/5Q2/6K1/8/8/8/8/8 b - - 0 1",
      },
      {
        type: "quiz",
        text: "Bu pozitsiyada qora yuradi. Bu qanday holat?",
        fen: "7k/5Q2/6K1/8/8/8/8/8 b - - 0 1",
        options: ["Mat", "Pat", "Shoh berilgan"],
        answer: 1,
        explanation: "Qora shohga shoh berilmagan, lekin u yura oladigan xavfsiz katak yo'q. Bu pat — durang.",
      },
      {
        type: "move",
        text: "Yutib turgan tomon patga yo'l qo'ymasligi kerak. Pat qilmasdan, bir yurishda mat qiling.",
        fen: "7k/8/6K1/8/8/8/8/5Q2 w - - 0 1",
        goal: "mate",
        hint: "Farzinni sakkizinchi gorizontga olib boring.",
        success: "Mat! f7 ga yurganingizda pat bo'lardi.",
      },
    ],
  },
  {
    slug: "rokirovka",
    stage: 0,
    title: "Rokirovka",
    summary: "Shoh va ruhning maxsus yurishi.",
    steps: [
      {
        type: "text",
        text: "Rokirovka — shoh va ruhning birgalikdagi maxsus yurishi. Shoh ruh tomonga ikki katak yuradi, ruh esa shoh ustidan sakrab, uning yoniga turadi. Rokirovka shohni xavfsiz joyga olib boradi.",
        fen: "8/8/8/8/8/8/8/R3K2R w KQ - 0 1",
        arrows: [
          ["e1", "g1"],
          ["e1", "c1"],
        ],
      },
      {
        type: "move",
        text: "Qisqa rokirovka qiling: shohni g1 ga yuring.",
        speech: "Qisqa rokirovka qiling: shohni g bir katakka yuring.",
        fen: "r3k2r/pppppppp/8/8/8/8/PPPPPPPP/R3K2R w KQkq - 0 1",
        solutions: ["e1g1"],
        success: "To'g'ri! Ruh f1 ga o'tdi.",
      },
      {
        type: "move",
        text: "Endi uzun rokirovka qiling: shohni c1 ga yuring.",
        speech: "Endi uzun rokirovka qiling: shohni c bir katakka yuring.",
        fen: "r3k2r/pppppppp/8/8/8/8/PPPPPPPP/R3K2R w KQkq - 0 1",
        solutions: ["e1c1"],
        success: "To'g'ri! Ruh d1 ga o'tdi.",
      },
      {
        type: "quiz",
        text: "Qaysi holatda rokirovka qilib bo'lmaydi?",
        options: [
          "Shoh yoki shu ruh avval yurgan bo'lsa",
          "Taxtada farzinlar bo'lsa",
          "O'yinning 10-yurishidan keyin",
        ],
        answer: 0,
        explanation: "Shoh ham, ruh ham avval yurmagan bo'lishi kerak. Shuningdek: shohga shoh berilmagan bo'lishi, shoh o'tadigan kataklar hujum ostida bo'lmasligi va shoh bilan ruh orasida dona bo'lmasligi kerak.",
      },
    ],
  },
  {
    slug: "yolda-urish",
    stage: 0,
    title: "Yo'lda urish",
    summary: "Piyodaning maxsus urishi.",
    steps: [
      {
        type: "text",
        text: "Raqib piyodasi birinchi yurishida ikki katak yurib, sizning piyodangiz yoniga kelib to'xtasa, uni xuddi bir katak yurgandek urib olishingiz mumkin. Buni faqat darhol, keyingi yurishda qilish mumkin.",
        fen: "8/8/8/3pP3/8/8/8/8 w - d6 0 1",
        arrows: [["e5", "d6"]],
      },
      {
        type: "move",
        text: "Qora piyoda hozirgina d7 dan d5 ga yurdi. Uni yo'lda urib oling.",
        speech: "Qora piyoda hozirgina d yettidan d beshga yurdi. Uni yo'lda urib oling.",
        fen: "4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 2",
        solutions: ["e5d6"],
        hint: "Piyodangizni d6 katakka qiyshiq yuring.",
        success: "To'g'ri! Qora piyoda taxtadan olindi.",
      },
    ],
  },
  {
    slug: "piyoda-aylanishi",
    stage: 0,
    title: "Piyodaning aylanishi",
    summary: "Oxirgi gorizontga yetgan piyoda boshqa donaga aylanadi.",
    steps: [
      {
        type: "text",
        text: "Oxirgi gorizontga yetgan piyoda o'sha zahoti farzin, ruh, fil yoki otga aylanadi. Ko'pincha eng kuchli dona — farzin tanlanadi.",
        fen: "4k3/1P6/8/8/8/8/8/4K3 w - - 0 1",
        arrows: [["b7", "b8"]],
      },
      {
        type: "move",
        text: "Piyodani oxirgi gorizontga suring va farzinga aylantiring.",
        fen: "4k3/1P6/8/8/8/8/8/4K3 w - - 0 1",
        solutions: ["b7b8q"],
        hint: "Piyodani b8 ga suring, keyin farzinni tanlang.",
        success: "Ajoyib! Endi sizda yangi farzin bor.",
      },
    ],
  },
];
